/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScoresIndexRouteImport } from './routes/scores/index'
import { Route as ScoresScoreIdRouteImport } from './routes/scores/$scoreId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresIndexRoute = ScoresIndexRouteImport.update({
  id: '/scores/',
  path: '/scores/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresScoreIdRoute = ScoresScoreIdRouteImport.update({
  id: '/scores/$scoreId',
  path: '/scores/$scoreId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/scores/$scoreId': typeof ScoresScoreIdRoute
  '/scores/': typeof ScoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/scores/$scoreId': typeof ScoresScoreIdRoute
  '/scores': typeof ScoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/scores/$scoreId': typeof ScoresScoreIdRoute
  '/scores/': typeof ScoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/scores/$scoreId' | '/scores/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/scores/$scoreId' | '/scores'
  id: '__root__' | '/' | '/about' | '/scores/$scoreId' | '/scores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ScoresScoreIdRoute: typeof ScoresScoreIdRoute
  ScoresIndexRoute: typeof ScoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores/': {
      id: '/scores/'
      path: '/scores'
      fullPath: '/scores/'
      preLoaderRoute: typeof ScoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores/$scoreId': {
      id: '/scores/$scoreId'
      path: '/scores/$scoreId'
      fullPath: '/scores/$scoreId'
      preLoaderRoute: typeof ScoresScoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ScoresScoreIdRoute: ScoresScoreIdRoute,
  ScoresIndexRoute: ScoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
