/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScoresIndexRouteImport } from './routes/scores/index'
import { Route as ScoresScoreIdRouteImport } from './routes/scores/$scoreId'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresIndexRoute = ScoresIndexRouteImport.update({
  id: '/scores/',
  path: '/scores/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresScoreIdRoute = ScoresScoreIdRouteImport.update({
  id: '/scores/$scoreId',
  path: '/scores/$scoreId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/_auth/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/_auth/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/scores/$scoreId': typeof ScoresScoreIdRoute
  '/scores/': typeof ScoresIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/signup/': typeof AuthSignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/scores/$scoreId': typeof ScoresScoreIdRoute
  '/scores': typeof ScoresIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/signup': typeof AuthSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/scores/$scoreId': typeof ScoresScoreIdRoute
  '/scores/': typeof ScoresIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/scores/$scoreId'
    | '/scores/'
    | '/login/'
    | '/signup/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/scores/$scoreId' | '/scores' | '/login' | '/signup'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/scores/$scoreId'
    | '/scores/'
    | '/_auth/login/'
    | '/_auth/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ScoresScoreIdRoute: typeof ScoresScoreIdRoute
  ScoresIndexRoute: typeof ScoresIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores/': {
      id: '/scores/'
      path: '/scores'
      fullPath: '/scores/'
      preLoaderRoute: typeof ScoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores/$scoreId': {
      id: '/scores/$scoreId'
      path: '/scores/$scoreId'
      fullPath: '/scores/$scoreId'
      preLoaderRoute: typeof ScoresScoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ScoresScoreIdRoute: ScoresScoreIdRoute,
  ScoresIndexRoute: ScoresIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
